### ISSUE TITLE
Feature Request: Add the ability to use Eufy’s new security products

### ISSUE THREAD

**Issue by David-Alton** [sebmos/homebridge-eufy#5]
Eufy recently released new security products (cameras and door sensors). Would it be possible to add those to HomeBridge?

**Comment by sebmos** [comment]
Unfortunately, I don't have either a camera or the door sensors - but if somebody has them, they're very welcome to contribute code to the [node-eufy-api](https://github.com/sebmos/node-eufy-api) package, or create their own!

**Comment by pdfowler** [comment]
I played around with integrating with the _Security_ products (cameras, entry sensors, etc) but didn't get too far. Something of note is that these products all fall under a separate API than implemented in the node-eufy-api package.

This repo: https://github.com/FuzzyMistborn/python-eufy-security has made some good progress, but it still seems early going.

**Comment by sebmos** [comment]
Thanks for the link - I've subscribed to the API documentation thread and will see if there's anything that can be done.
The previous problem still applies, though - I don't have one of Eufy's security products.

**Comment by DanielsCode** [comment]
+1 motion sensors and door/window sensor would be great. Also to get the "state" of the Alarm system from the EufyApp. They also provide a hardware panel to change these states.

**Comment by z3r0** [comment]
Any updates to add support for Eufy entry sensors as well as motion sensors?

**Comment by cms365** [comment]
+1

Have the Wired Doorbell 2K and would love to integrate into Homebridge!

**Comment by PeteBurgess** [comment]
Looks like someone's done a ton of Eufy work here... tragically well past my ability to understand.

https://github.com/bropat/ioBroker.eufy-security/tree/master/admin

**Comment by technikosoldat** [comment]
Hello, does the plugin work with door sensor ? Thanks
